/**
 * Search and social metadata.
 *
 * A local clinic lives or dies on the map pack, so the structured data here is
 * deliberately complete: a Dentist entity with real coordinates, machine-
 * readable opening hours, a service catalogue, breadcrumbs on every inner
 * page, FAQ markup where there are questions, and Article markup on posts.
 * All of it is generated from /data — nothing to maintain by hand.
 */
import {
  clinic,
  site,
  absoluteUrl,
  siteUrl,
  locale,
  serviceItems,
  clinicHours,
  getFounder
} from '@/lib/data';

const compact = (value) => {
  if (Array.isArray(value)) {
    const cleaned = value.map(compact).filter((entry) => entry != null);
    return cleaned.length ? cleaned : undefined;
  }
  if (value && typeof value === 'object') {
    const cleaned = Object.fromEntries(
      Object.entries(value)
        .map(([key, entry]) => [key, compact(entry)])
        .filter(([, entry]) => entry != null && entry !== '')
    );
    return Object.keys(cleaned).length ? cleaned : undefined;
  }
  return value === '' || value == null ? undefined : value;
};

const ORG_ID = () => `${siteUrl}/#clinic`;

/* ---------- page metadata ---------- */

export function ogImageUrl(image) {
  if (image) return image.startsWith('http') ? image : absoluteUrl(image);
  if (site.openGraph?.image) {
    return site.openGraph.image.startsWith('http')
      ? site.openGraph.image
      : absoluteUrl(site.openGraph.image);
  }
  /* Generated by app/opengraph-image.js from the clinic name and tagline. */
  return absoluteUrl('/opengraph-image');
}

/**
 * Builds a complete Metadata object: canonical URL, Open Graph and Twitter
 * cards. Every page uses it so no route can ship without a canonical or a
 * social preview.
 */
export function pageMetadata({
  title,
  description,
  path = '/',
  image,
  type = 'website',
  publishedTime,
  authors,
  noIndex = false
} = {}) {
  const url = absoluteUrl(path);
  const resolvedDescription = description || clinic.seo?.description || '';
  const resolvedImage = ogImageUrl(image);

  return compact({
    title,
    description: resolvedDescription,
    alternates: { canonical: url },
    robots: noIndex ? { index: false, follow: false } : undefined,
    openGraph: {
      title: title || clinic.seo?.title,
      description: resolvedDescription,
      url,
      siteName: clinic.identity?.legalName,
      locale: locale.openGraph,
      type,
      publishedTime,
      authors,
      images: [{ url: resolvedImage, width: 1200, height: 630, alt: clinic.identity?.legalName }]
    },
    twitter: {
      card: 'summary_large_image',
      title: title || clinic.seo?.title,
      description: resolvedDescription,
      images: [resolvedImage]
    }
  });
}

/* ---------- structured data ---------- */

function openingHoursSpecification() {
  return clinicHours()
    .filter((slot) => slot.opens && slot.closes && Array.isArray(slot.dayOfWeek) && slot.dayOfWeek.length)
    .map((slot) => ({
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: slot.dayOfWeek,
      opens: slot.opens,
      closes: slot.closes
    }));
}

/** The clinic itself. Referenced by @id from every other node so Google links them. */
export function clinicSchema() {
  const address = clinic.contact?.address || {};
  const rating = clinic.seo?.aggregateRating;
  const founder = getFounder();

  return compact({
    '@context': 'https://schema.org',
    '@type': 'Dentist',
    '@id': ORG_ID(),
    name: clinic.identity?.legalName,
    alternateName: clinic.identity?.name,
    description: clinic.identity?.longDescription || clinic.seo?.description,
    slogan: clinic.identity?.tagline,
    url: siteUrl,
    logo: ogImageUrl(clinic.identity?.logo?.src),
    image: ogImageUrl(clinic.about?.interiorImage?.src),
    telephone: clinic.contact?.phone,
    email: clinic.contact?.email,
    priceRange: clinic.seo?.priceRange,
    foundingDate: clinic.identity?.established,
    currenciesAccepted: locale.currency,
    address: {
      '@type': 'PostalAddress',
      streetAddress: address.line1,
      addressLocality: address.city,
      addressRegion: address.state,
      postalCode: address.postalCode,
      addressCountry: address.countryCode || address.country
    },
    geo:
      Number.isFinite(address.geo?.latitude) && Number.isFinite(address.geo?.longitude)
        ? {
            '@type': 'GeoCoordinates',
            latitude: address.geo.latitude,
            longitude: address.geo.longitude
          }
        : undefined,
    hasMap: address.mapsUrl,
    openingHoursSpecification: openingHoursSpecification(),
    sameAs: (clinic.socials || []).map((s) => s.href).filter((href) => /^https?:/.test(href || '')),
    founder: founder
      ? { '@type': 'Person', name: founder.name, jobTitle: founder.role }
      : undefined,
    aggregateRating:
      rating?.value > 0 && rating?.count > 0
        ? {
            '@type': 'AggregateRating',
            ratingValue: rating.value,
            reviewCount: rating.count,
            bestRating: 5,
            worstRating: 1
          }
        : undefined,
    makesOffer: serviceItems().map((service) => ({
      '@type': 'Offer',
      itemOffered: {
        '@type': 'MedicalProcedure',
        name: service.title,
        description: service.excerpt,
        url: absoluteUrl(`/services/${service.slug}`)
      }
    }))
  });
}

export function websiteSchema() {
  return compact({
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${siteUrl}/#website`,
    url: siteUrl,
    name: clinic.identity?.legalName,
    inLanguage: locale.htmlLang,
    publisher: { '@id': ORG_ID() }
  });
}

/** `crumbs` is the same array the PageHero takes, so the two can never drift apart. */
export function breadcrumbSchema(crumbs = [], homeLabel = 'Home') {
  const trail = [{ label: homeLabel, href: '/' }, ...crumbs];
  return compact({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((crumb, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: crumb.label,
      item: crumb.href ? absoluteUrl(crumb.href) : undefined
    }))
  });
}

export function faqSchema(items = []) {
  const questions = items.filter((item) => item?.q && item?.a);
  if (!questions.length) return null;
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: questions.map((item) => ({
      '@type': 'Question',
      name: item.q,
      acceptedAnswer: { '@type': 'Answer', text: item.a }
    }))
  };
}

export function articleSchema(post) {
  if (!post) return null;
  const published = Number.isNaN(Date.parse(post.date)) ? undefined : new Date(post.date).toISOString();
  return compact({
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.excerpt,
    image: ogImageUrl(post.image?.src),
    datePublished: published,
    dateModified: published,
    articleSection: post.category,
    inLanguage: locale.htmlLang,
    author: { '@type': 'Person', name: post.author },
    publisher: { '@id': ORG_ID() },
    mainEntityOfPage: absoluteUrl(`/blog/${post.slug}`)
  });
}

export function serviceSchema(service) {
  if (!service) return null;
  return compact({
    '@context': 'https://schema.org',
    '@type': 'MedicalProcedure',
    name: service.title,
    description: service.description || service.excerpt,
    image: ogImageUrl(service.image?.src),
    url: absoluteUrl(`/services/${service.slug}`),
    provider: { '@id': ORG_ID() },
    howPerformed: Array.isArray(service.includes) ? service.includes.join('. ') : undefined
  });
}
